
services:
  postgres:
    image: postgres
    container_name: sample_music_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/data/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: sample_music_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    depends_on:
      - postgres

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sample_music_kafka
    ports:
      - "9092:9092"
    depends_on:
      - postgres
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: sample_music_zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  database-server:
    build:
      context: database-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  identity-server:
    build:
      context: identity-server
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  image-service:
    build:
      context: image-service
      dockerfile: Dockerfile
    ports:
      - "9020:9020"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  payment-service:
    build:
      context: payment-service
      dockerfile: Dockerfile
    ports:
      - "9040:9040"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  producer-service:
    build:
      context: producer-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  sound-service:
    build:
      context: sound-service
      dockerfile: Dockerfile
    ports:
      - "9030:9030"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres

  subscription-service:
    build:
      context: subscription-service
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    depends_on:
      - postgres
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://localhost:5432/postgres