server:
  port: 8765
spring:
  application:
    name: identity-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: identity-service
        url: /v3/api-docs

      - name: producer-service
        url: /producer-service/v3/api-docs

      - name: subscription-service
        url: /subscription-service/v3/api-docs

      - name: image-service
        url: /image-service/v3/api-docs

      - name: sound-service
        url: /sound-service/v3/api-docs

      - name: payment-service
        url: /payment-service/v3/api-docs