server:
  port: 9010
spring:
  application:
    name: subscription-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  data:
    jdbc:
      dialect: postgresql
springdoc:
  api-docs:
    path: /subscription-service/v3/api-docs
  swagger-ui:
    path: /subscription-service/swagger-ui.html
