server:
  port: 9020
spring:
  application:
    name: image-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
springdoc:
  api-docs:
    path: /image-service/v3/api-docs
  swagger-ui:
    path: /image-service/swagger-ui.html

